name: opencv
channels:
  - conda-forge
  - defaults
dependencies:
  - imutils=0.5.*
  - ipykernel=5.3.*
  - matplotlib=3.3.*
  - numpy=1.19.*
  - opencv=4.4.*
  - requests=2.24.*
conda env create -f environment/environment.yml
